//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAMMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _202554_tuning_Nissan_Skyline_GT_R_R35_Liberty_Walk_Nissan_GTR {
            get {
                object obj = ResourceManager.GetObject("202554-tuning-Nissan_Skyline_GT-R_R35-Liberty_Walk-Nissan_GTR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3c3ed3bacc6dbae2c611c83ed2e5c9e5 {
            get {
                object obj = ResourceManager.GetObject("3c3ed3bacc6dbae2c611c83ed2e5c9e5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9VDPtp7 {
            get {
                object obj = ResourceManager.GetObject("9VDPtp7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cjVvUNh {
            get {
                object obj = ResourceManager.GetObject("cjVvUNh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ferrari_Italia_Crystal_City_Car_and_Ferrari_California_2014_Orange_Neon_design_by_Tony_Kokhan_www_el_tony_com_ {
            get {
                object obj = ResourceManager.GetObject("Ferrari-Italia-Crystal-City-Car-and-Ferrari-California-2014-Orange-Neon-design-by" +
                        "-Tony-Kokhan-www.el-tony.com_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ferrari_Italia_Crystal_City_Car_and_Ferrari_California_2014_Orange_Neon_design_by_Tony_Kokhan_www_el_tony1 {
            get {
                object obj = ResourceManager.GetObject("Ferrari-Italia-Crystal-City-Car-and-Ferrari-California-2014-Orange-Neon-design-by" +
                        "-Tony-Kokhan-www.el-tony1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lamborghini_Aventador_Front_Crystal_City_Car_2014_Orange_Neon_design_by_Tony_Kokhan_www_el_tony_com_ {
            get {
                object obj = ResourceManager.GetObject("Lamborghini-Aventador-Front-Crystal-City-Car-2014-Orange-Neon-design-by-Tony-Kokh" +
                        "an-www.el-tony.com_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lamborghini_gallardo_wallpaper_images_logo_high_backgrounds_with_background_full_hd_pics_for_androids_ {
            get {
                object obj = ResourceManager.GetObject("lamborghini-gallardo-wallpaper-images-logo-high-backgrounds-with-background-full-" +
                        "hd-pics-for-androids-", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lamborghini_Logo_03 {
            get {
                object obj = ResourceManager.GetObject("Lamborghini-Logo-03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lamborghini_Logo_031 {
            get {
                object obj = ResourceManager.GetObject("Lamborghini-Logo-031", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lamborghini_Logo_032 {
            get {
                object obj = ResourceManager.GetObject("Lamborghini-Logo-032", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lamborghini_Logo_Color {
            get {
                object obj = ResourceManager.GetObject("Lamborghini-Logo-Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lamborghini_Logo_Color1 {
            get {
                object obj = ResourceManager.GetObject("Lamborghini-Logo-Color1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nissan_gtr_hd_wallpaper__1 {
            get {
                object obj = ResourceManager.GetObject("nissan-gtr-hd-wallpaper--1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pmh_lamborghinis {
            get {
                object obj = ResourceManager.GetObject("pmh_lamborghinis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thumb_1920_300837 {
            get {
                object obj = ResourceManager.GetObject("thumb-1920-300837", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
